### ISSUE TITLE
Shader Issue

### ISSUE THREAD

**Issue by ewokthegreat** [NBowlin/Unity_Coordinate_Mapping#2]
The textures don't show unless I switch the shaders to standard.

**Comment by beinz** [comment]
> The textures don't show unless I switch the shaders to standard.

i have same problem and solved

we need "Universal Render Pipeline"

make Universal Render Pipeline project 
or
1. install "Lightweight RP" at Package Manager (all packages)
2. Project -> Create -> Rendering -> Universal Render Pipeline -> Pipeline Asset(Forward Renderer) 
this makes UniversalRenderPipelineAsset and UniversalRenderPipelineAsset_Renderer
3. set UniversalRenderPipelineAsset  to edit->project settings -> Graphics -> Scriptable Renderer Pipeline Settings

Save

**Comment by NickBow** [comment]
Hi, sorry I missed this. But Beinz is correct. The project uses the new render pipelines, so the shaders should work with the Universal Render Pipeline or the High Definition Render Pipeline (Although I haven't tested that latter).

I will update the README. Thanks!
